services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 200m
          cpus: "1.0"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 200m
          cpus: "1.0"

networks:
  app-network:
    driver: bridge
